### ISSUE TITLE
Pull in open pull requests against old repository.

### ISSUE THREAD

**Issue by markhibberd** [markhibberd/riak-haskell-client#2]
- [x] janrain/riak-haskell-client#10
- [x] janrain/riak-haskell-client#19
- [x] janrain/riak-haskell-client#23
